### ISSUE TITLE
Obtener Trazabilidad - 404 not found

### ISSUE THREAD

**Issue by c0sm1cdus7** [romeroyonatan/py-andreani#1]
Buenos días.

Se que este no es el lugar, pero la verdad que no encuentro a nadie que sepa apuntarme en la dirección correcta.

Estoy teniendo dificultades con la API de Andreani. Consigo hacer casi todo, cotizar y realizar envíos, imprimir etiquetas, etc... Excepto conocer el estado de un envío.

Este es el url de la consulta: https://www.e-andreani.com/eAndreaniWSStaging/Service.svc?wsdl

Este es el XML que estoy enviando:

`<?xml version="1.0" encoding="UTF-8"?> <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://www.andreani.com.ar/req" xmlns:ns2="http://schemas.datacontract.org/2004/07/EAndreaniWS" xmlns:ns3="http://www.andreani.com.ar"> <env:Body> <ns3:ObtenerEstadoDistribucionCodificado> <ns3:EnviosConsultas> <ns1:CodigoCliente>CL0003750</ns1:CodigoCliente> <ns1:Envios> <ns2:Envio> <ns2:IdentificadorCliente></ns2:IdentificadorCliente> <ns2:NumeroAndreani>*10000000555465</ns2:NumeroAndreani> </ns2:Envio> </ns1:Envios> </ns3:EnviosConsultas> </ns3:ObtenerEstadoDistribucionCodificado> </env:Body> </env:Envelope>`

Y el servidor responde con el estado 404 not found.

![image](https://user-images.githubusercontent.com/20582332/34262573-89f4363a-e64b-11e7-84ba-9b2131331e6f.png)

Estoy haciendo algo mal?

Si alguien me puede apuntar en el camino correcto se lo agradecería.

Saludos,

**Comment by romeroyonatan** [comment]
Hola franalt,
Esta biblioteca nunca entró en producción porque mi cliente finalmente no utilizó el servicio de Andreani. Igualmente lo volví a revisar por este issue para tratar de darte una mano.

En principio el Endpoint sigue funcionando:
```python
In [23]: api.consultar_trazabilidad('*10000000555465')
Out[23]: 
{'envios': {'envio': [{'eventos': {'evento': [{'estado': Envío no ingresado,
       'fecha': datetime.datetime(2017, 12, 8, 14, 51, 53, tzinfo=<suds.sax.date.FixedOffsetTimezone object at 0x7fed1e218a58>),
       'id_estado': 30,
       'id_motivo': -1,
       'motivo': None,
       'sucursal':  }]},
    'fecha_alta': datetime.datetime(2017, 12, 8, 14, 51, 53, tzinfo=<suds.sax.date.FixedOffsetTimezone object at 0x7fed1e218518>),
    'nombre_envio': Constancia de Envío,
    'nro_andreani': *10000000555465}]},
 'numero_envio': None}
```

Así que descartamos que sea un tema de ellos.

Este es el Endpoint que usa esta biblioteca: `https://www.e-andreani.com/eAndreaniWSStaging/Service.svc?wsdl`

Por lo que veo, yo utilizo el método `ObtenerTrazabilidadSinClienteCodificado`, desconozco porque utilizé este método. Es lo unico distinto a lo que vos estas haciendo

**Comment by c0sm1cdus7** [comment]
Muchas gracias por tu respuesta!

Lamentablemente, sigo sin poder realizar la consulta, cambie el método a ObtenerTrazabilidadSinClienteCodificado y sigo recibiendo 404 como respuesta de la consulta.

![image](https://user-images.githubusercontent.com/20582332/34297736-abc85ce8-e6f8-11e7-936c-a3971c9d88d1.png)

Me encantaría poder utilizar tu biblioteca, pero utilizo Node.JS en la aplicación. 

Intentaste alguna vez realizar la consulta utilizando AJAX o XMLHttpRequest? Quizás no es posible con este método, pero es lo que estoy utilizando para todas mis consultas y es el único servicio que no consigo hacer funcionar.

Si no te es mucha molestia, podrías probar de hacer la consulta con alguno de esos métodos? Me darías una enorme mano.

**Comment by romeroyonatan** [comment]
Me gusta el software que usas para las consultas, ¿cual es?

**Comment by c0sm1cdus7** [comment]
Es Postman, lo podes descargar desde el Chrome Store, o desde su pagina para Mac, Linux o Windows https://www.getpostman.com/. Esta muy bueno, podes probar API's sin dar muchas vueltas

**Comment by c0sm1cdus7** [comment]
Bueno, finalmente logré ponerme en contacto con Andreani y notaron que tenían un error de su lado, sumado a un error en la documentación.

El URL de la consulta de Trazabilidad es:

`https://www.e-andreani.com/eAndreaniWSStaging/Service.svc/soap12`

Y el XML es:

```
<?xml version="1.0" encoding="UTF-8"?>

<env:Envelope
    xmlns:env="http://www.w3.org/2003/05/soap-envelope"
    xmlns:ns1="http://www.andreani.com.ar/req"
    xmlns:ns2="http://www.andreani.com.ar">
    <env:Body>
        <ns2:ObtenerTrazabilidadCodificado>
            <ns2:NroPieza>
                <ns1:NroPieza></ns1:NroPieza>
                <ns1:NroAndreani>NUMERO DE ENVIO</ns1:NroAndreani>
                <ns1:CodigoCliente>CODIGO DE CLIENTE</ns1:CodigoCliente>
            </ns2:NroPieza>
        </ns2:ObtenerTrazabilidadCodificado>
    </env:Body>
</env:Envelope>
```

Codigo Javascript completo:

```
xmlhttp = new XMLHttpRequest();

xmlhttp.open('POST', 'https://cors-anywhere.herokuapp.com/https://www.e-andreani.com/eAndreaniWSStaging/Service.svc/soap12', true);

var strRequest = '...XML DE LA CONSULTA...';

xmlhttp.setRequestHeader('Content-Type', 'application/soap+xml; charset=utf-8; action="http://www.andreani.com.ar/IService/ObtenerTrazabilidadCodificado"');

xmlhttp.onreadystatechange = function () {
	if (xmlhttp.readyState == 4) {
		console.log(xmlhttp.responseText);
	}
};

xmlhttp.send(strRequest);
```

Utilizo un Proxy para no tener problemas con la utilización de CORS, se puede ver en el URL de la consulta.

`https://cors-anywhere.herokuapp.com`

Codigo Node.JS:

```
var parseString = require('xml2js').parseString;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var xmlhttp = new XMLHttpRequest();

xmlhttp.open('POST', 'https://www.e-andreani.com/eAndreaniWSStaging/Service.svc/soap12', true);

var strRequest = '...XML DE LA CONSULTA...';

xmlhttp.setRequestHeader('Access-Control-Allow-Headers', '*');
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', '*');
xmlhttp.setRequestHeader('Content-Type', 'application/soap+xml; charset=utf-8; action="http://www.andreani.com.ar/IService/ObtenerTrazabilidadCodificado"');

xmlhttp.onreadystatechange = function () {
	if (xmlhttp.readyState == 4) {
		response.success(estados);
	}
};

xmlhttp.send(strRequest);
```

Muchas gracias por tu ayuda. Dejo el código por si alguien esta en la misma.

Saludos!
